version: '3'

services:
  db:
    container_name: odm2admindb
    image: mdillon/postgis:9.5
    restart: always
    expose:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  app:
    container_name: odm2adminapp
    restart: always
    build: 
      context: ../../
      dockerfile: ./docker/odm2admin/Dockerfile
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
    - POSTGRES_HOST=db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=test
    - POSTGRES_NAME=odm2
    - POSTGRES_PORT=5432
    volumes:
      - ../../docker/docker-deploy/settings:/ODM2-Admin/templatesAndSettings/settings

  redis:
    container_name: odm2adminredis
    restart: always
    image: redis:latest
    expose:
      - "6379"

volumes:
  dbdata: